package view;

public enum PossibleAction {

  GOWEST, GOEAST, GONORTH, GOSOUTH, INVENTORY, ATTACK, RUN, OPEN,CLOSE, DRINKWATER, DRINKJUICE, WEARARMOR1, WEARARMOR2, WEARARMOR3, USESWORD1, USESWORD2, USESWORD3, UNUSESWORD1, UNUSESWORD2, UNUSESWORD3, UNUSEARMOR1, UNUSEARMOR2, UNUSEARMOR3;
}
